### PR TITLE
Allow response filtering in `instrumentHandlerValue`.

### PR DESCRIPTION
**Pull request by fisx**
As announced in #44.  Haddocks explain what this is about.

### CODE REVIEW

**Comment by fisx** [comment]
(Please ping me if you think I should be doing anything about the travis failures, I think they are unrelated.)

**Comment by fimad** [comment]
I think these travis errors are actually legit (not sure why the other PR had flakes....)

This is failing to build with GHC 7.8.4:
```
src/Network/Wai/Middleware/Prometheus.hs:86:18:
    Not in scope: ‘pure’
```

**Comment by fisx** [comment]
hum yes, didn't test ghc7.  let's see if this commit will help?

**Comment by fisx** [comment]
...  *now* the travis errors look unrelated to me?

**Comment by fisx** [comment]
I would fix them with some CPP pragmas if you like.  Here or separately.

**Comment by fimad** [comment]
Looks good to me, thanks for this!
